/* Auto-generated by scripts/gen-user-init.sh (stub). */
#ifndef _KAIROS_USER_INIT_BLOB_H
#define _KAIROS_USER_INIT_BLOB_H

#include <stddef.h>

static const unsigned char user_init_elf[] = {0};
static const size_t user_init_elf_size = 0;

#endif /* _KAIROS_USER_INIT_BLOB_H */
