#!/usr/bin/env bash
set -euo pipefail

ARCH=${1:-riscv64}
if [[ "$ARCH" != "riscv64" ]]; then
  echo "gen-user-init: only riscv64 supported (got $ARCH)" >&2
  exit 0
fi

OUT_DIR="build/${ARCH}/user"
OBJ="${OUT_DIR}/init.o"
ELF="${OUT_DIR}/init.elf"
HEADER="kernel/core/proc/user_init_blob.h"

mkdir -p "${OUT_DIR}"

/usr/sbin/llvm-mc -filetype=obj -triple=riscv64-unknown-elf \
  user/init/init.S -o "${OBJ}"
/usr/sbin/ld.lld -T user/init/linker.ld -o "${ELF}" "${OBJ}"

python3 - <<'PY'
import pathlib

data = pathlib.Path("build/riscv64/user/init.elf").read_bytes()
header = pathlib.Path("kernel/core/proc/user_init_blob.h")

lines = []
lines.append("/* Auto-generated by scripts/gen-user-init.sh */")
lines.append("#ifndef _KAIROS_USER_INIT_BLOB_H")
lines.append("#define _KAIROS_USER_INIT_BLOB_H")
lines.append("")
lines.append("#include <stddef.h>")
lines.append("")
lines.append("static const unsigned char user_init_elf[] = {")

line = "    "
for i, b in enumerate(data):
    entry = f"0x{b:02x},"
    if len(line) + len(entry) > 78:
        lines.append(line)
        line = "    " + entry
    else:
        line += entry
if line.strip():
    lines.append(line)

lines.append("};")
lines.append("static const size_t user_init_elf_size = sizeof(user_init_elf);")
lines.append("")
lines.append("#endif /* _KAIROS_USER_INIT_BLOB_H */")
lines.append("")

header.write_text("\n".join(lines))
PY

echo "Generated ${HEADER} from ${ELF}"
