/**
 * kairos/config.h - Kernel configuration
 */

#ifndef _KAIROS_CONFIG_H
#define _KAIROS_CONFIG_H

/*
 * Memory Configuration
 */
#define CONFIG_PAGE_SIZE 4096
#define CONFIG_PAGE_SHIFT 12

#define CONFIG_MIN_MEMORY_MB 64
#define CONFIG_RECOMMENDED_MB 256

#define CONFIG_KERNEL_HEAP_INIT_MB 4
#define CONFIG_KERNEL_HEAP_MAX_MB 64

/*
 * Process Configuration
 */
#define CONFIG_MAX_PROCESSES 256
#define CONFIG_KERNEL_STACK_SIZE (16 * 1024)     /* 16 KB */
#define CONFIG_USER_STACK_SIZE (8 * 1024 * 1024) /* 8 MB virtual */
#define CONFIG_MAX_FILES_PER_PROC 64
#define CONFIG_MAX_THREADS 1024

#if (CONFIG_KERNEL_STACK_SIZE % CONFIG_PAGE_SIZE) != 0
#error "CONFIG_KERNEL_STACK_SIZE must be a multiple of CONFIG_PAGE_SIZE"
#endif
#define CONFIG_KERNEL_STACK_PAGES (CONFIG_KERNEL_STACK_SIZE / CONFIG_PAGE_SIZE)
#if CONFIG_KERNEL_STACK_PAGES == 1
#define CONFIG_KERNEL_STACK_ORDER 0
#elif CONFIG_KERNEL_STACK_PAGES == 2
#define CONFIG_KERNEL_STACK_ORDER 1
#elif CONFIG_KERNEL_STACK_PAGES == 4
#define CONFIG_KERNEL_STACK_ORDER 2
#elif CONFIG_KERNEL_STACK_PAGES == 8
#define CONFIG_KERNEL_STACK_ORDER 3
#else
#error "CONFIG_KERNEL_STACK_SIZE requires unsupported page order"
#endif
#ifndef CONFIG_ELF_INTERP_LOAD_BIAS_BASE
#define CONFIG_ELF_INTERP_LOAD_BIAS_BASE 0x0000002000000000ULL
#endif
#ifndef CONFIG_ELF_INTERP_LOAD_BIAS_STRIDE
#define CONFIG_ELF_INTERP_LOAD_BIAS_STRIDE (2ULL * 1024 * 1024)
#endif
#ifndef CONFIG_ELF_INTERP_LOAD_BIAS_SLOTS
#define CONFIG_ELF_INTERP_LOAD_BIAS_SLOTS 32
#endif

/*
 * Scheduler Configuration
 */
#define CONFIG_HZ 100          /* Timer ticks per second */
#define CONFIG_MAX_CPUS 16

/*
 * File System Configuration
 */
#define CONFIG_MAX_MOUNTS 16
#define CONFIG_MAX_OPEN_FILES 1024
#define CONFIG_PATH_MAX 256
#define CONFIG_NAME_MAX 64
#define CONFIG_SYMLINK_MAX 8 /* Max symlink depth */
#define CONFIG_DCACHE_MAX 4096
#define CONFIG_DCACHE_NEG_TTL_SEC 2

/*
 * Network Configuration
 */
#define CONFIG_NET_BUFFER_SIZE (2 * 1024 * 1024)
#define CONFIG_MAX_SOCKETS 256

/*
 * IPC Configuration
 */
#define CONFIG_PIPE_SIZE (64 * 1024) /* 64 KB pipe buffer */

/*
 * Signal Configuration
 */
#define CONFIG_NSIG 32 /* Number of signals */

/*
 * Debug Configuration
 */
#define CONFIG_DEBUG 0
#define CONFIG_VERBOSE 0
#ifndef CONFIG_KERNEL_TESTS
#define CONFIG_KERNEL_TESTS 0
#endif
#ifndef CONFIG_KERNEL_FAULT_INJECT
#define CONFIG_KERNEL_FAULT_INJECT 0
#endif
#ifndef CONFIG_KERNEL_TEST_MASK
#define CONFIG_KERNEL_TEST_MASK 0x7FF
#endif
#ifndef CONFIG_DRIVER_TEST_IRQ_SOAK_ONLY
#define CONFIG_DRIVER_TEST_IRQ_SOAK_ONLY 0
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_DURATION_SEC
#define CONFIG_KERNEL_SOAK_PR_DURATION_SEC 900
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_FAULT_PERMILLE
#define CONFIG_KERNEL_SOAK_PR_FAULT_PERMILLE 3
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_MAX_ITERS
#define CONFIG_KERNEL_SOAK_PR_MAX_ITERS 0
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_SUITE_MASK
#define CONFIG_KERNEL_SOAK_PR_SUITE_MASK 0xFF
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_SCHED_EVERY
#define CONFIG_KERNEL_SOAK_PR_SCHED_EVERY 8
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_FAULT_EVERY
#define CONFIG_KERNEL_SOAK_PR_FAULT_EVERY 4
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_MIN_RUNS_PER_SUITE
#define CONFIG_KERNEL_SOAK_PR_MIN_RUNS_PER_SUITE 1
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_SUITE_TIMEOUT_SEC
#define CONFIG_KERNEL_SOAK_PR_SUITE_TIMEOUT_SEC 120
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_FAULT_WARMUP_HITS
#define CONFIG_KERNEL_SOAK_PR_FAULT_WARMUP_HITS 128
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_FAULT_FAIL_BUDGET
#define CONFIG_KERNEL_SOAK_PR_FAULT_FAIL_BUDGET 2048
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_FAULT_PROBE_OPS
#define CONFIG_KERNEL_SOAK_PR_FAULT_PROBE_OPS 2048
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_UACCESS_FAULT_PROBE_OPS
#define CONFIG_KERNEL_SOAK_PR_UACCESS_FAULT_PROBE_OPS 1024
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_IPC_CAP_DEEP_ROUNDS
#define CONFIG_KERNEL_SOAK_PR_IPC_CAP_DEEP_ROUNDS 2
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_IPC_CAP_NOISE_THREADS
#define CONFIG_KERNEL_SOAK_PR_IPC_CAP_NOISE_THREADS 3
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_IPC_CAP_NOISE_YIELD_MAX
#define CONFIG_KERNEL_SOAK_PR_IPC_CAP_NOISE_YIELD_MAX 8
#endif
#ifndef CONFIG_KERNEL_SOAK_PR_IPC_CAP_NOISE_STOP_TIMEOUT_SEC
#define CONFIG_KERNEL_SOAK_PR_IPC_CAP_NOISE_STOP_TIMEOUT_SEC 3
#endif
#ifndef CONFIG_EMBEDDED_INIT
#define CONFIG_EMBEDDED_INIT 0
#endif
#ifndef CONFIG_PMM_DEBUG
#define CONFIG_PMM_DEBUG 1
#endif
/*
 * PCP mode:
 *   0 = disabled
 *   1 = debug (enabled with integrity checks)
 *   2 = enabled
 */
#ifndef CONFIG_PMM_PCP_MODE
#define CONFIG_PMM_PCP_MODE 1
#endif
#ifndef CONFIG_PMM_REMOTE_FREE_BATCH
#define CONFIG_PMM_REMOTE_FREE_BATCH 32
#endif
#ifndef CONFIG_PMM_REMOTE_FREE_HIGH
#define CONFIG_PMM_REMOTE_FREE_HIGH 512
#endif
#ifndef CONFIG_PMM_INTEGRITY_PANIC
#define CONFIG_PMM_INTEGRITY_PANIC 0
#endif
/* #define CONFIG_SLUB_DEBUG           1 */

/*
 * Lock debugging
 */
#ifndef CONFIG_DEBUG_LOCKS
#define CONFIG_DEBUG_LOCKS 0
#endif
#ifndef CONFIG_LOCKDEP
#define CONFIG_LOCKDEP 0
#endif
#ifndef CONFIG_IPC_POLL_HINT_STRICT
#define CONFIG_IPC_POLL_HINT_STRICT 0
#endif

/*
 * Architecture-specific (set by build system)
 */
#ifndef CONFIG_ARCH
#define CONFIG_ARCH "riscv64"
#endif

#endif /* _KAIROS_CONFIG_H */
